development:
  sessions:
    default:
      database: atheneum-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: atheneum-test
      hosts:
        - localhost:27017