---
- hosts: api-servers
  remote_user: root
  vars:
    deploy_user: atheneum
    deploy_group: atheneum
  roles:
    - base
    - deploy-user
    - git
    - nginx
    - rbenv
    - passenger
    - mongodb
    - atheneum-api

# TODO:
# Setup deploy user
# Install ruby for deploy user
# Setup NTP

# Setup nginx
# Setup Passenger
# Setup api.athenuem.io
# Setup atheneum.io / www.atheneum.io

# Setup nginx to run with passenger on api.atheneum.io
# Set up AWS keys

# Setup mongoDB

# Setup log rotate for
# nginx
# atheneum app

